name: CI Pipeline

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: npm install
      - name: Rodar ESLint
        run: npm run lint
      - name: Rodar Testes
        run: npm test
